apiVersion: apps/v1
kind: Deployment
metadata:
  name: blood-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blood-frontend
  template:
    metadata:
      labels:
        app: blood-frontend
    spec:
      containers:
        - name: blood-frontend
          image: vsharanya/blood-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blood-frontend
spec:
  selector:
    app: blood-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
